### PR TITLE
DotNetStandard 1.6

### PR DESCRIPTION
**Pull request by NVentimiglia**
DotNetStandard is the best way for making cross-platform plugins. It should replace the WinRT and the DotNetCore linker projects (I would test WinRT). Maybe even the Unity 3.5 project sometime in 2018.

### CODE REVIEW

**Comment by RevenantX** [comment]
This solution file (and project) will work in Xamarin Studio (Monodevelop)?

**Comment by NVentimiglia** [comment]
The documentation says it will work... but it did not. The test project did not load either.

Should I set up a separate solution for the standard library so it does not conflict ?

@RevenantX

**Comment by RevenantX** [comment]
@NVentimiglia Yes, this will be cool. Like in NetCore project.

**Comment by RevenantX** [comment]
@NVentimiglia I can merge?

**Comment by NVentimiglia** [comment]
@RevenantX Yeah, after it goes green.

**Comment by RevenantX** [comment]
@NVentimiglia thanks!)

**Pull request merged**
