### PR TITLE
Added .NET5+ Member Trimming Annotations

### PR DESCRIPTION
**Pull request by Sewer56**
This PR adds annotations for [.NET 5+ Assembly Member Trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming).  

In a real application, I have observed the following size reduction:  
`95,744` -> `70,656` bytes.  (-26.21%)

This is actually less than usually observed with trimming, though within expectation due to the library's internal design.

### CODE REVIEW

**Comment by RevenantX** [comment]
@Sewer56 this increases complexity of library support to reduce size just by 25kb? I don't think this has much sense.

**Comment by Sewer56** [comment]
Yeah, it's a bit unfortunate, some greater savings are potentially possible with some minor changes; e.g. making some components like `NatPunchModule` optional; but at the moment, it's not something worth optimising for as the library itself is already small in the first place.  

That said, even taking that into consideration, there are still some good valid reasons for adding trimming annotations to libraries outside of that.  

- Annotating LiteNetLib for trimming is necessary to make trimming libraries that extend LNL safe for trimming.
  - Specifically, trimmer warnings bubble up from the framework, up the dependency chain; so in order for libraries which extend/make use of LNL to be safely trimmable, LNL needs to be trimmable.
- It is really not much maintenance overhead at all.  
  - In practice, 95% of the time you only really need to annotate new endpoints that use reflection. Other trimmer unfriendly usages are quite rare in my experience.  
  - The built-in Trim Analyzer is pretty good at detecting trim warnings without need to publish these days; so you'd see warnings immediately in the VS Warnings window.  
  - Ensuring trimming is good is also somewhat possible to automate; for example I've been considering adding [Trim Warnings](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2001) as errors in my own projects so PRs and other code changes wouldn't pass CI/CD until warnings are resolved.

**Comment by Sewer56** [comment]
To add to the previously posted list of reasons, in a recent change [all assemblies will be trimmed with linking by default when trimming is enabled in .NET 7](https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-7/#trimming-and-nativeaot-all-assemblies-trimmed-by-default).

**Comment by kant2002** [comment]
Would be great to have this PR landed, to make NativeAOT experience more pleasant. And soon we will have WASI-SDK in .NET 8 where size would matter a bit more.

**Comment by Sewer56** [comment]
:pray:

**Pull request merged**
