### PR TITLE
Added Peek method for char.

### PR DESCRIPTION
**Pull request by guilhermeluizsp**
Added the missing Peek method for char on NetDataReader.

### CODE REVIEW

**Comment by RevenantX** [comment]
Hi! Thanks! But please use BitConverter.ToChar without casting.

**Comment by RevenantX** [comment]
I will fix this)

**Comment by guilhermeluizsp** [comment]
Oh, sorry, I created the method based on the GetChar method (which used ushort), so I thought it was a design decision. Thanks for merging anyway =)

**Comment by RevenantX** [comment]
@guilhermeluizsp that was my mistake)

**Pull request merged**
