### PR TITLE
Updated comments for clarity as per issue #322.

### PR DESCRIPTION
**Pull request by JasperCiti**

### CODE REVIEW

**Comment by RevenantX** [comment]
@JasperCiti Thanks! But replace tabs to spaces (there also .editorconfig for some IDEs to automatically set spaces)

**Comment by JasperCiti** [comment]
Do you have an .editorconfig that you prefer to use?  Maybe consider adding it to your git repository?

**Comment by RevenantX** [comment]
@JasperCiti it already here https://github.com/RevenantX/LiteNetLib/blob/master/.editorconfig

**Comment by RevenantX** [comment]
>tabs to spaces 

Commit message: 
>Replaced spaces with tabs.

**Comment by JasperCiti** [comment]
Sorry, I misunderstood your comment. I though you said the problem is that my **IDE** replaces tabs to spaces. That is why I did it the other way around because I noticed half the lines were tabs and half were spaces. Anyways, I installed your .editorconfig and hopefully this won't happen again.

**Pull request merged**
