### PR TITLE
Improve NTP response parsing

### LINKED ISSUE #234: NTP improve time correction
NTP protocol has defined a [Clock synchronization algorithm](https://en.wikipedia.org/wiki/Network_Time_Protocol#Clock_synchronization_algorithm), but the `NtpRequest` class simply gets the server time and ignores other time informations. I would like to have a better (proper) implementation, e.g. see [Guerilla NTP](https://github.com/robertvazan/guerrillantp) or [Platform.NET NTP implementations](https://github.com/platformdotnet/Platform/tree/master/src/Platform/Network/Time).

IMHO is could be enough to take [`NtpPacket` from Guerilla NTP](https://github.com/robertvazan/guerrillantp/blob/master/GuerrillaNtp/NtpPacket.cs) and the logic is included in the `NtpPacket.CorrectionOffset` property.

**Library version**: 0.8indev

### PR DESCRIPTION
**Pull request by xmedeko**
Fix #234

### CODE REVIEW

**Comment by RevenantX** [comment]
@xmedeko thanks for PR!) Can you add new files to other projects too (LiteNetLibStandard and LiteNetLibNetCore). And i think you can remove all set methods from NtpPacket.

**Comment by xmedeko** [comment]
Added missing files to LiteNetLibStandard and LiteNetLibNetCore csproj. I've kept the setters to keep the code similar to the GuerillaNtp form which I have copied that.

**Comment by RevenantX** [comment]
@xmedeko 
>  I've kept the setters to keep the code similar to the GuerillaNtp form which I have copied that.

I understand but this methods have no sense in this use case.

**Comment by SmiggsGDog** [comment]
Just a heads up, Guerilla NTP appears to be Apache 2.0 licensed.

**Comment by xmedeko** [comment]
@RevenantX OK, I may RFCT the `NtpPacket` code to fit to the use case used in LiteNetLib.

**Comment by xmedeko** [comment]
@RevenantX OK, I have RFCT the `NtpPacket` code to fit to the use case used in LiteNetLib.

**BUT** I have found a bug in `NtpRequest` that if the response is not received the socket stays open. So, I have change the usage, so the user has to call `Create`, `Send` and `Close` manually. So the user must decide, when to close the socket. E.g. in the callback or after some timeout.

**Comment by xmedeko** [comment]
@robertvazan May I include the `NtpPacket` from https://github.com/robertvazan/guerrillantp into this project under the MIT license, please? Your project is under the Apache2 which is more restrictive. Thank you very much.

**Comment by robertvazan** [comment]
@xmedeko I answered your email, but just to state it publicly here: Yes, of course, you can.

**Comment by xmedeko** [comment]
@RevenantX @SmiggsGDog I've added doc to `NetPacket` and hope the legal stuff is ok now 😏

**Pull request merged**
