### PR TITLE
Add Generic Get/Put for INetSerializable objects

### PR DESCRIPTION
**Pull request by jblai**
Add Generic Get/Put for INetSerializable objects. This will let Serialize/Deserialize INetSerializable object in other INetSerializable object. Therefore, helping with code reusability and organization.

### CODE REVIEW

**Comment by jblai** [comment]
Usage example:

//Regular INetSerializable class
public Foo : INetSerializable
{
    public int Value1;

    public void Serialize(NetDataWriter writer)
    {
        writer.Put(Value1);
    }

    public void Deserialize(NetDataReader reader)
    {
        Value1 = reader.GetInt();
    }
}

//INetSerializable that De/Serialize another INetSerializable as one of its members
public Bar: INetSerializable
{
    public Foo FooObject;
    public int Value2;


    public void Serialize(NetDataWriter writer)
    {
        writer.Put(FooObject);
        writer.Put(Value2);
    }

    public void Deserialize(NetDataReader reader)
    {
        FooObject= reader.Get<Foo>();
        Value2 = reader.GetInt();
    }
}

**Comment by RevenantX** [comment]
Cool! But replace tabs to spaces.

**Comment by jblai** [comment]
Will do! Sorry about that, we use tabs where i work and this is actually the first time contributing on a open source project.

**Comment by RevenantX** [comment]
@jblai but remember that new T() calls Activator.CreateInstance which calls reflection and works very slow

**Comment by jblai** [comment]
Interesting, I didn't know that. I've just seen this kind of functionality on UNET and DarkRift and found it useful in terms of compositing serializable objects. Would there be another way to achieve this? 
Or should we put a warning in the documentation tags.
In the project i'm working in, we're not sending at constant and rapid intervals, just on demand in a average of 2-3 messages sent per second between server client. It's probably why we were not concerned much yet about it, but i'll take into consideration if you say so.

**Comment by jblai** [comment]
@RevenantX Was thinking about it this weekend. I guess the best way to achieve something similar is to implement GetFoo()/GetBar() as an extension to NetDataWriter for each the classes that implements INetSerializable. In that case, the actual constructor can be called instead of new T().
Kinda hard to put this into library... or maybe it can be documented in the documentation comments for Get<T>()?

**Pull request merged**
