### PR TITLE
Exception policy #89

### PR DESCRIPTION
**Pull request by marsermd**
Added typed exceptions as discussed.

### CODE REVIEW

**Comment by RevenantX** [comment]
@marsermd thanks!) Fix please "<para>" doc comment.

**Comment by marsermd** [comment]
@RevenantX I guess you've meant to make the line breaks this way?

Or you don't like the multi-line docs in general?

**Comment by RevenantX** [comment]
@marsermd i meant you have typo in "\<para\>" instead of "\<param\>"

**Comment by marsermd** [comment]
@RevenantX I don't believe I have one:)
Tag "<para>" is a valid tag for a [paragraph](https://msdn.microsoft.com/en-us/library/x640hcd2(v=vs.90).aspx). And I meant to use it.

I've double checked that there is no misuse of that tag in my code or in the whole project.

**Comment by RevenantX** [comment]
@marsermd oh. Sorry)

**Pull request merged**
