### PR TITLE
Separation NetLayer

### PR DESCRIPTION
**Pull request by Kaladrius2trip**
Implement net layer as generic argument
Feature added combine layer mechanism as LayerUnifier. 

Example usage:
```csharp
NetManager srv = new NetManager<LayerUnifier<XorEncryptLayer, Crc32cLayer>>(srvListener, 
                LayerUnifier.Make(new XorEncryptLayer("secret_key"), new Crc32cLayer()));
```

P.S. Includes PR #399

### CODE REVIEW

**Comment by Kaladrius2trip** [comment]
If make some(all) layer as struct. We may have more code performance.

**Comment by RevenantX** [comment]
@Kaladrius2trip you can combine layers in much easier way. There is too much strange additions and interfaces (which are slow in IL2CPP) and strange virtual methods. Also public internal packets.

**Comment by Kaladrius2trip** [comment]
Il2CPP AOT compiled generic is slowly ?

**Comment by RevenantX** [comment]
@Kaladrius2trip interface calls is slow. Doesn't know about generics. Also you are used .tt which isn't supported in many places

**Comment by RevenantX** [comment]
@Kaladrius2trip if you need multiple layers - just create class that combines them inside in your code.

**Comment by Kaladrius2trip** [comment]
@RevenantX .tt once generated. Supported in VS and Rider. Rider doen't support .net 3.5 and pass many errors. So... 
Interface virtual mapping uses if u implement this as class. But i'll recommend use struct.

**Comment by RevenantX** [comment]
@Kaladrius2trip library almost always used as source code inside unity or godot project.

**Comment by RevenantX** [comment]
I will rewrite layers in better way later (layer per channel)

**Pull request closed without merging**
