### PR TITLE
Net core tests

### PR DESCRIPTION
**Pull request by Kaladrius2trip**
Add duplicate tests for net core runner for better coverage
Update NUnit to actual version

### CODE REVIEW

**Comment by Kaladrius2trip** [comment]
Add connection failed unit test

**Comment by Kaladrius2trip** [comment]
@RevenantX please look test "NetPeerDisconnectAll"
Infinite loop in PollEvents

**Comment by Kaladrius2trip** [comment]
I think this is related to this issue [Issues-163](https://github.com/RevenantX/LiteNetLib/issues/163)

**Comment by Kaladrius2trip** [comment]
I fixed it. Very temporary solution.
Add line `netPeer.Shutdown(null, 0, 0, true);` in NetManager after disconnect package handling.

**Comment by RevenantX** [comment]
Thanks for PR.

**Comment by RevenantX** [comment]
@Kaladrius2trip i know about "problem" with disconnection state. And i fixed it, but not pushed code changes yet.

**Comment by Kaladrius2trip** [comment]
@RevenantX Remove please my draft code after fix it. )

**Pull request merged**
