### PR TITLE
Reduce GC Alloc

### PR DESCRIPTION
**Pull request by forestrf**
I am using LiteNetLib with Unity and the profiler was showing some bits on GC Alloc when sending messages.

By iterating lists instead of dictionaries and pooling byte arrays I was able to remove a lot of it. It is now 0 for the method SendToAll, that was being called nearly every frame.

To do it I used a pool that resembles the NetPacket pool that was implemented with an Stack and tracked all the `new byte[]` that I was able to find to also use a pool and recycle them before they were deferenced.

Thank you for this library, the code is clean and it works without problems.

### CODE REVIEW

**Comment by RevenantX** [comment]
Thanks for contributing :). Must to do some review and then merge.

**Comment by RevenantX** [comment]
There some things that i must tune.
1)  ```new T();``` - calls ```Activator.CreateInstance()``` that can be slow.
2) Agressive pooling can eat some critical memory (on mobile devices). So there must be option.

**Comment by forestrf** [comment]
So it needs to be an option, and the pool should not use generics
I didn't know about Activator.CreateInstance being slow, that is a problem.
Also, the pooling of the array bytes right now could be simplified by returning arrays of the wanted size or bigger to prevent that many instances. I really don't like seeing gc generated on the profiler :P

Thank you for the library. It is way way easier to read and understand than Lidgren Network

**Comment by RevenantX** [comment]
>  I really don't like seeing gc generated on the profiler :P
I agree about gc generated in "Update" method. But about "Connect" packets and some other that sends very rare - do not worry)

**Comment by RevenantX** [comment]
Fixed. You can see code in master.

**Comment by forestrf** [comment]
Thank you! Awesome library, thx!

**Pull request merged**
