### PR TITLE
serializer now can serialize boxed types

### PR DESCRIPTION
**Pull request by sorencoder**
You can now have a packet that holds an `object` property and everytime you can have different value boxed in it.

I added two test cases for `object` and `object[]` property serialization.

### CODE REVIEW

**Comment by Eideren** [comment]
Switch case on objects for variable types is a C# 7.0 feature, replace it for lower versions.
A typecode switch could work ?

**Comment by sorencoder** [comment]
@Eideren 

> Switch case on objects for variable types is a C# 7.0 feature, replace it for lower versions.
A typecode switch could work ?

Thank you for pointing out. I replaced it with C# 4.0 version.

**Comment by RevenantX** [comment]
@sorencoder thanks) But i cannot imagine situation where this can be helpful... Can you provide some example?)

**Comment by sorencoder** [comment]
@RevenantX well, The reason that I needed this kind of serialization was that I wanted client to be able to "Invoke" methods on server (and vice versa). I have this class:
`public class NetworkCall
{
public string Name {get; set;}
public object[] Parameters {get; set;}
}`
 Client creates `NetworkCall` with method name and parameters, serializes it and sends it over network, and server invokes that method when it receives the `NetworkCall`

**Comment by sorencoder** [comment]
@RevenantX 
Another example is when you want to create some kind of key->simple_value dictionary.
```
public class Data
{
    public string Header{get; set;}
    public string[] Keys {get; set;}
    public object[] Values {get; set;}
}
```

**Comment by RevenantX** [comment]
@sorencoder You want create RPC over `NetSerializer`?) This is not best idea. You will get bad performance. 
And this is not obvious that `object` methods of `NetDataWriter` (and `NetSerializer`) accept only simple types.

**Comment by sorencoder** [comment]
@RevenantX Can you please explain why I will get bad performance? what do you recommend for creating RPC?
I don't use them every frame though, I use them for mechanics like Signup, Login, Adding and Removing from matchmaking and functions like that.

> And this is not obvious that object methods of NetDataWriter (and NetSerializer) accept only simple types.

how about changing methods name to `PutSimpleObject` and `GetSimpleObject` ?

**Comment by RevenantX** [comment]
@sorencoder there already exists some High-Level libraries over LiteNetLib. For example https://github.com/Saishy/TinyBirdNet-Unity 
I created NetSerializer especially for RPC like usage. But with precise arguments (without "objects") and methods like `CallRPC(string methodName, params object[] args)`. 
With NetPacketProcessor subscribe and send you will get almost RPC with less possible errors)

**Comment by Randy5300** [comment]
Hi @RevenantX . I've been using the library a couple of days now and need to say that I'm impressed. But I'm trying to achieve the same that @sorencoder is trying. Could you please provide an example where I can invoke a method with parameters?

**Comment by RevenantX** [comment]
@Randy5300 there is no builtin RPC. You can look how its implemented in TinyBirdNet.
And uploaded `NetPacketProcessor` example: https://github.com/RevenantX/LiteNetLib/blob/master/LibSample/PacketProcessorExample.cs

**Comment by Randy5300** [comment]
Hi @RevenantX  Thanks for your NetPacketProcessor example. When I tried to edit that example to my likings I've received an error: "LiteNetLib.Utils.ParseException: 'Undefined packet in NetDataReader'". Could you please provide an example where you split the client and server instead of having it in the same file?

Thanks in advance.

**Comment by RevenantX** [comment]
@Randy5300 send your contacts (telegram, discord). This is not right place for this questions)

**Comment by Randy5300** [comment]
@RevenantX my discord is: Randy5300#4085
I'll remove my comments after.

**Comment by RevenantX** [comment]
@sorencoder sorry but i cannot accept this PR, because this breaks idea of simple `NetDataWriter`/`NetDataReader` and anyway introduce ambiguity. Better add this as extension method in your code or make derived class. And look at `PacketProcessorExample` ;)

**Comment by pha3z** [comment]
RevenantX,
I checked out the NetSerializer, and I wanted to applaud you for keeping it simple.  I'm glad you stood your ground against Sorencoder's wishes.  I agree with you: I cannot fathom a sound reason for a good serializer to serialize boxed properties.  If you have data that is so publicly accessible that it's getting stored and sent over a network, then storing it in boxed properties seems dubious and questionable to begin with.  Sorencoder could have easily written some kind of command class that would map data from variables to methods and completely eliminated the need for what he was asking—not to mention it would probably produce better code.

As a p.s.: I come from the "Getter/setters are Evil" camp. :)

**Comment by RevenantX** [comment]
@pha3z 
> As a p.s.: I come from the "Getter/setters are Evil" camp. :)

I'm from the same camp. But for serialization (using reflection) { get; set; } works faster because i can cache delegates to get/set methods. And they works faster than SetValue/GetValue

**Comment by pha3z** [comment]
Oh wow.  Interesting!  You've just educated me!

**Comment by sorencoder** [comment]
@pha3z 
> Sorencoder could have easily written some kind of command class that would map data from variables to methods and completely eliminated the need for what he was asking
I didn't ask for anything. I had a **working** implementation that suited my needs. I just wanted to share it with others who might have the same need.
A rule of thumb is, "if it ain't broke, don't fix it". the implementation wasn't broke. so I didn't need to **easily** write **some kind of** command class.

**Pull request closed without merging**
